# Generated by Django 3.1.3 on 2020-11-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20201121_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_articles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_articles',
        ),
    ]
