# Generated by Django 3.1.3 on 2020-12-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_auto_20201203_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
