# Generated by Django 3.1.3 on 2020-12-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_auto_20201208_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
    ]
