# Generated by Django 3.1.3 on 2020-12-13 04:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_auto_20201213_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='Write content here...'),
        ),
    ]
